In [4]:
import numpy as np
from collections import defaultdict
from collections import deque

In [15]:
class GraphAlgorithms:
    def __init__(self, n, p):
        #initialize random graph
        self.graph = [
            [] for i in range(n)
        ]
        self.weights = [
            [] for i in range(n)
        ]
        edges = set()
        for i in range(n):
            for j in range(n):
                if i == j:
                    continue
                if (min(i,j),max(i,j)) in edges:
                    continue
                if np.random.uniform() < p:
                    self.graph[i].append(j)
                    self.graph[j].append(i)
                    edges.add((min(i,j),max(i,j)))
                    weight = np.random.uniform(1,5)
                    self.weights[i].append(weight)
                    self.weights[j].append(weight)
        print(self.graph)
        print(self.weights)
        
    def bfs(self, v):
        visited = set()
        visited.add(v)
        bfs_queue = deque()
        bfs_queue.append((v,0))
        prev_level = 0
        while bfs_queue:
            node, level = bfs_queue.popleft()
            for i in self.graph[node]:
                if i not in visited:
                    bfs_queue.append((i,level+1))
                    visited.add(i)
            if level > prev_level:
                print('')
                prev_level = level
            print(node, end=' ')
            
    def dfs(self,v):
        visited = set()
        visited.add(v)
        dfs_stack = []
        dfs_stack.append(v)
        while dfs_stack:
            node = dfs_stack.pop()
            for i in self.graph[node]:
                if i not in visited:
                    dfs_stack.append(i)
                    visited.add(i)
            print(node)
            
    def djikstra(self,x,y):
        open_set = {}
        closed_set = {}
        
        closed_set[x] = 0
        for v,d in zip(self.graph[x], self.weights[x]):
            open_set[v] = d
        
        while y not in closed_set:
            _minv, _mind = 100, 100
            for v,d in open_set.items():
                if d < _minv:
                    _minv, _mind = v,d
            closed_set[v] = d
            for v2,d2 in zip(self.graph[v], self.weights[v]):
                if v2 in closed_set:
                    continue
                if v2 in open_set:
                    open_set[v2] = min(open_set[v2], d + d2)
                else:
                    open_set[v2] = d + d2
                    
        return closed_set[y]
        
    def belman_ford(self,x,y):
        

In [24]:
g = GraphAlgorithms(10,.3)

[[1, 3, 6, 8], [0, 2, 5, 6, 8, 9], [1, 3, 6, 7, 9, 4], [0, 2, 8], [2, 6, 9], [1, 8], [0, 1, 2, 4, 7, 9], [2, 6, 8, 9], [0, 1, 3, 5, 7], [1, 2, 4, 6, 7]]
[[3.69126221305386, 4.99668155679548, 4.000095979949503, 1.6250134657693422], [3.69126221305386, 1.68897954388884, 3.809851409316544, 3.8134730025231547, 4.009549186419452, 4.540747463722189], [1.68897954388884, 2.7536040234263774, 1.9489181036236145, 2.9482758684064776, 4.747790196339244, 4.703348189618589], [4.99668155679548, 2.7536040234263774, 1.4204121853175655], [4.703348189618589, 4.263918882367343, 3.128245293999244], [3.809851409316544, 2.4793887876618554], [4.000095979949503, 3.8134730025231547, 1.9489181036236145, 4.263918882367343, 2.8995322759309143, 2.32879044754388], [2.9482758684064776, 2.8995322759309143, 3.8521864408828317, 4.501160543732115], [1.6250134657693422, 4.009549186419452, 1.4204121853175655, 2.4793887876618554, 3.8521864408828317], [4.540747463722189, 4.747790196339244, 3.128245293999244, 2.32879044754388, 

In [21]:
g.bfs(0)

0 
4 1 6 9 
2 3 8 7 5 

In [22]:
g.dfs(0)

0
9
7
8
5
3
2
6
1
4


In [25]:
g.djikstra(0,9)

9.97836045038429

# Binary Search

In [26]:
x = [1,2,3,4,5,6,7,8,9,10,11]

In [27]:
def bs(x,nums):
    lidx = 0
    ridx = len(nums)
    
    while lidx < ridx:
        _mid = (lidx + ridx) // 2
        if nums[_mid] == x:
            return _mid
        elif nums[_mid] < x:
            lidx = _mid + 1
        else:
            ridx = _mid
    return -1

In [28]:
bs(1,x)

0

In [29]:
bs(9,x)

8

In [30]:
bs(12,x)

-1

In [31]:
bs(4,x)

3

In [32]:
for i in range(13):
    print(bs(i,x))

-1
0
1
2
3
4
5
6
7
8
9
10
-1


# Sorting

### MergeSort

In [35]:
def ms(nums):
    if len(nums) == 1:
        return nums
    else:
        _mid = len(nums)//2
        l = ms(nums[:_mid])
        r = ms(nums[_mid:])
        new_array = [0] * len(nums)
        lidx = 0
        ridx = 0
        for i in range(len(nums)):
            if lidx >= len(l):
                new_array[i] = r[ridx]
                ridx += 1
            elif ridx >= len(r):
                new_array[i] = l[lidx]
                lidx += 1
            else:
                if r[ridx] > l[lidx]:
                    new_array[i] = l[lidx]
                    lidx += 1
                else:
                    new_array[i] = r[ridx]
                    ridx += 1
        return new_array

In [38]:
ms(np.random.normal(size=10))

[-1.4851715557645242,
 -0.7083397985777468,
 -0.3805886686921884,
 0.3362493529199843,
 0.5541565792464159,
 0.9977382441704182,
 1.0480251863382608,
 1.1757408358747465,
 1.5371268233488105,
 1.8050930965308418]

In [41]:
def insertion_sort(nums):
    for i in range(1,len(nums)):
        for j in reversed(range(1, i+1)):
            if nums[j] < nums[j-1]:
                nums[j-1], nums[j] = nums[j], nums[j-1]
    return nums

In [42]:
insertion_sort(np.random.normal(size=10))

array([-2.32100162, -1.69922148, -1.05543323, -0.49694769, -0.30904386,
       -0.28843885, -0.22200837, -0.14692284,  0.25890106,  2.65689558])

In [55]:
np.random.randint(2)

1

## Quicksort

In [96]:
def qs(nums):
    def helper(lidx, ridx):
        if ridx - lidx < 2:
            return
        pivot = lidx + np.random.randint(ridx - lidx)
        nums[pivot], nums[ridx-1] = nums[ridx-1], nums[pivot]
        pos = lidx
        
        for i in range(lidx, ridx-1):
            if nums[i] < nums[ridx-1]:
                nums[i], nums[pos] = nums[pos], nums[i]
                pos += 1
        nums[ridx-1], nums[pos] = nums[pos], nums[ridx-1]

        helper(lidx, pos)
        helper(pos + 1, ridx)
    helper(0,len(nums))
            

In [97]:
a = np.random.normal(size=10)

In [98]:
a

array([-0.15155092,  1.1846767 ,  1.42616943,  0.35064352,  0.87281754,
        0.03737156, -1.08004904, -1.88809384,  1.04370759,  0.56212101])

In [99]:
qs(a)

In [100]:
a


array([-1.88809384, -1.08004904, -0.15155092,  0.03737156,  0.35064352,
        0.56212101,  0.87281754,  1.04370759,  1.1846767 ,  1.42616943])

In [ ]:
def heapify(x):
    def helper(top_element):
        elem = top_element
        while elem*2 < len(x):
            child1 = elem*2
            child2 = elem*2+1
            if child2 < len(x):
                if x[child1] < x[elem]:
                    if x[child2] < x[child1]:
                        x[child2], x[elem] = x[elem], x[child2]
                        elem = child2
                